apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  selector:
    matchLabels:
      app: django
  replicas: 1    
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: ljk0509/ljk_django:movie_app
        ports:
        - containerPort: 8000
